var relationshipCode = {
  "01": "Spouse",
  "03": "Father or Mother",
  "04": "Grandfather or Grandmother",
  "05": "Grandson or Granddaughter",
  "06": "Uncle or Aunt",
  "07": "Nephew or Niece",
  "08": "Cousin",
  "09": "Adopted Child",
  "10": "Foster Child",
  "11": "Son-in-law or Daughter-in-law",
  "12": "Brother-in-law or Sister-in-law",
  "13": "Mother-in-law or Father-in-law",
  "14": "Brother or Sister",
  "15": "Ward",
  "16": "Stepparent",
  "17": "Stepson or Stepdaughter",
  "18": "Self",
  "19": "Child",
  "20": "Employee",
  "21": "Unknown",
  "23": "Sponsored Dependent",
  "24": "Dependent of a Minor Dependent",
  "25": "Ex-spouse",
  "26": "Guardian",
  "31": "Court Appointed Guardian",
  "34": "Other Adult",
  "38": "Collateral Dependent",
  "39": "Organ Donor",
  "40": "Cadaver Donor",
  "53": "Life Partner",
  "60": "Annuitant",
  "D2": "Trustee",
  "G8": "Other Relationship",
  "G9": "Other Relative",
  "22": "Handicapped Dependent",
  "29": "Significant Other",
  "36": "Emancipated Minor",
  "41": "Injured Plaintiff",
  "43": "Insured Child Has No Financial Responsibility",
  "32": "Mother",
  "33": "Father",
  "NB": "Newborn"
}

exports.translate = function(code){
  return relationshipCode[code];
}
